### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by eseceve** [beerjs/santiago#10]
Sería interesante que alguien contara su experiencia de cómo y qué midió para mejorar la perf de javascripts (css) en su proyecto.
Quizás tirar tips como "evitar usar `for-in`, el clásico `for` es más rápido que incluso que el `forEach`", etc.

**Comment by quest** [comment]
+1

**Comment by juanbrujo** [comment]
hecho, edición #15 julio 2016 https://github.com/beerjs/santiago/issues/27
