### ISSUE TITLE
Tema: Testing

### ISSUE THREAD

**Issue by quest** [beerjs/santiago#2]
Cómo dice el título, para una próxima instancia propongo este tema.
# eso

**Comment by juanbrujo** [comment]
:+1: osea va a ser en eClass? podriamos comenzar a poner fecha!

**Comment by quest** [comment]
Obvio! necesito que definamos una fecha, cantidad de personas y horario, para pedir el permiso.

**Comment by juanbrujo** [comment]
bien ordenemos esto.
- cantidad: el lugar lo define
- fecha: el dueño del lugar lo define (los miercoles y jueves son buenos dias)
- hora: despues del job (desde 19:00 a 19:30 y q dure max. 3 hrs.)

**Comment by quest** [comment]
- Cantidad: 15-20 buen número en mi caso
- Fecha: Miércoles 24
- Hora: 19:30 a 22:00 hrs.

**Comment by juanbrujo** [comment]
@quest confirmas la fecha? para comenzar a cambiar el sitio de beerjs y preparar la inscripcion, tu me dices si se usa el mismo o prefieres otro.

**Comment by quest** [comment]
Confirmado!
