### ISSUE TITLE
Material Gráfico (fotos)

### ISSUE THREAD

**Issue by juanbrujo** [beerjs/santiago#22]
Hola, les pido por favor quienes tengan fotos que las vayan subiendo aqui para comenzar a poblar con contenido de las ediciones anteriores el sitio de beerjs.cl? pueden tirarlas como comentario, indicando el mes porfavor. Automaticamente tendrán credito por ellas, salvo que me mencionen lo contrario.

Gracias!

**Comment by gmq** [comment]
![20160106_203644](https://cloud.githubusercontent.com/assets/472791/14092817/e4e1d7ec-f51f-11e5-847d-3d950d4f936b.jpg)
![20160106_205829](https://cloud.githubusercontent.com/assets/472791/14092857/1e0ec43a-f520-11e5-9eaf-b66a2bf4def1.jpg)
![20160106_211414](https://cloud.githubusercontent.com/assets/472791/14092818/e4e2e4e8-f51f-11e5-8c5a-fabc144a96e4.jpg)
![20160106_213037](https://cloud.githubusercontent.com/assets/472791/14092820/e4e34d98-f51f-11e5-88be-d3fd97fc8ae8.jpg)

Enero en Yapo
