### ISSUE TITLE
Grupo en Meetup

### ISSUE THREAD

**Issue by quest** [beerjs/santiago#3]
Con el fin de organizar a los participantes y eventos venideros, propongo utilizar la plataforma Meetup. Ayuda en la organización y promoción de los eventos.
# eso

**Comment by juanbrujo** [comment]
necesito argumentos, ya q por ahora este canal + slack + guestlistapp.com han servido.

**Comment by quest** [comment]
**Difusión y organización**. Si al final no va a ser de pago este evento por el momento (_y a futuro creo yo_), pero si sería ideal que la difusión salga un poco de Slack y se incluya mas gente.

**Comment by juanbrujo** [comment]
@quest bien pero notese q los espacios hasta ahora estan limitados por capacidad; le primero tenia hasta 15 personas, el de eclass tendras tb problemas de limite y en multinet aun menos. hay q saber controlar eso. concuerdo q la difusion debe ser mas amplia pero podemos usar otras RRSS (un canal de TW para comenzar). enfin dejo el tema abierto

**Comment by quest** [comment]
Dale, entiendo :)

**Comment by hectorpalmatellez** [comment]
Quizás para esta versión, como habrá más espacio, sea bueno ampliar la convocatoria usando Meetup, ¿no? :eyes:

**Comment by quest** [comment]
más espacio?

**Comment by hectorpalmatellez** [comment]
Eso decía el rumor.

**Comment by juanpablob** [comment]
Para no tener problemas de espacio, sugiero hablar con fundación Telefónica o con los amigos de StartUp Chile para que pasen el Movistar Innova una vez al mes para hacer nuestra junta. A ellos les interesa mucho pues agregaría valor a los muchos de los desarrolladores que están trabajando ahí todos los días y además nos ayuda a hacer crecer la comunidad y hacer más ricas las conversas y experiencias. Un win-win!

**Comment by juanbrujo** [comment]
@juanpablob creo q los q mencionas ya trabajan con js chile o js meetup chile, algo asi. o ofrecemos valor agregado -diferencial- o unimos fuerzas. por ahora los cupos q tenemos se llenan pero la lista corre y no se ha necesitado mas de 20-30 personas por edicion. ayer tuvimos nuevos asistentes, si siguen asistiendo y vuelven los q frecuentes q faltaron estariamos pensando en ampliar.

evaluemoslo en la prox. edicion q se esperan 30 cupos fijos. pero deberiamos preguntarnos: que diferencia beerjs de otra meetup? la cerveza? los asistentes? la experiencia?
