### ISSUE TITLE
VueJS 

### ISSUE THREAD

**Issue by raulghm** [beerjs/santiago#37]
Porque es Osom!! ( ^..^)ﾉ

https://vuejs.org
https://github.com/vuejs/awesome-vue

**Comment by fforres** [comment]
Hace tiempo que tengo ganas de meter mano a VUE.
Estaría bueno ver una carla/intro/workshop/hands-on :D

**Comment by juanbrujo** [comment]
visto en la edicion de diciembre 2016, cerrando por ahora.
