### ISSUE TITLE
Tema: scraping

### ISSUE THREAD

**Issue by quest** [beerjs/santiago#4]
Propongo este tema y se me ocurre que @narzerus puede hablar sobre _yakuza_.

**Comment by RafaelVidaurre** [comment]
Encantado

**Comment by juanbrujo** [comment]
buen tema, anotado. Hagamos q el host del beerjs decida el tema de ese encuentro bueno?

**Comment by RafaelVidaurre** [comment]
Roger that

**Comment by juanbrujo** [comment]
visto en la edicion n5 de BeerJS Santiago https://github.com/beerjs/santiago/issues/12, cerrando.

**Comment by eseceve** [comment]
@juanbrujo podrías editar tu último comentario y para que no se mal entiendan los links? 
Si pones `edicion n5` es mejor que `edicion #5` pq el # genera un link a un issue nada que ver.

**Comment by RafaelVidaurre** [comment]
jaja details!
