### ISSUE TITLE
Convenciones y buenas prácticas

### ISSUE THREAD

**Issue by eseceve** [beerjs/santiago#9]
Por lo visto son varios los que trabajan solos y escriben el código como quieran, lo que no necesariamente es malo pero las convenciones están para simplificar la vida, creo.
En la última beerjs alguien dijo que había revisado la de [airbnb](https://github.com/airbnb/javascript) y otro dijo que había leído mucho al respecto.
Creo que una charla sobre esto sería positivo para los que están empezando o quienes aún no deciden que guía de estilos seguir.

**Comment by javiera-vasquez** [comment]
+1 a este tema, soy uno de los que trabaja solo y seria bueno conocer como es el flujo del resto.

**Comment by juanbrujo** [comment]
@s0wk en la primera edicion tratamos el tema de workflow porq precisamente queria saber como trabajaban el resto, [mi aporte](https://speakerdeck.com/csslab/workflow-custom-para-desarrollos-frontend)

**Comment by Zenemig** [comment]
+1 absolutamente, los autodidactas que nos toca trabajar solos adolecemos de esto >.<

**Comment by katguzmann** [comment]
+1
